name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    defaults:
      run:
        shell: bash -l {0}

    name: PyCC Test ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Create Psi4 Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: p4dev
        environment-file: devtools/conda-envs/psi.yaml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: true

    - name: Environment Information
      run: |
        conda info
        conda list --show-channel-urls
        hash -r
        env

    - name: Install Psi4
      run: |
        conda info
        conda list --show-channel-urls
        conda install psi4 python=${{ matrix.python-version }} -c psi4/label/dev
        ls -l $CONDA

    - name: Test Psi4 Python Loading
      run: |
        export PATH=$CONDA_PREFIX/bin:$PATH
        export PYTHONPATH=$CONDA_PREFIX/lib:$PYTHONPATH
        python -c 'import psi4'

    - name: Install PyCC and Deps
      run: |
        env
        export PATH=$CONDA_PREFIX/bin:$PATH
        export PYTHONPATH=$CONDA_PREFIX/lib:$PYTHONPATH
        python -m pip install .
        python -m pip install opt_einsum
        python -m pip install scipy
        conda list

    - name: PyTest
      run: |
        pytest -v --cov=pycc --cov-report=xml --color=yes pycc/tests/test_013_lpnocc.py

    - name: CodeCov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-pycc
